// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Tax Calculator
// Component: frontend/src/app/components/features/TaxCalculatorPage.tsx
//
// Co-located Dexie schema slice. Re-exports the page-relevant tables from
// the shared `db` instance so feature code only sees what it owns.
// The actual schema versions / .stores() live in `src/lib/database.ts`
// to keep a single IndexedDB per app.

import { db } from '../../lib/database';

export const taxCalculatorDb = {
  taxCalculations: db.taxCalculations,
} as const;

export type TaxCalculatorDb = typeof taxCalculatorDb;

// --- end auto-generated ---

