// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Tax Calculator - offline-first query helpers.
//
// Rules:
//   * Writes go to Dexie first with syncStatus = 'pending'.
//   * Background sync worker reconciles with /api/v1/* later.
//   * Reads are user-scoped where the table has a userId/ownerId.
//   * Monetary writes that mutate balances MUST be confirmed by the
//     server-authoritative endpoint before being marked synced.

import { taxCalculatorDb } from './db';

export const taxCalculatorQueries = {
  /** List all local rows in `taxCalculations`. */
  listTaxCalculations: async () => taxCalculatorDb.taxCalculations.toArray(),

  /** Get a single `taxCalculation` by primary key. */
  getTaxCalculation: async (id: number | string) => taxCalculatorDb.taxCalculations.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createTaxCalculation: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return taxCalculatorDb.taxCalculations.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateTaxCalculation: async (id: number | string, patch: Record<string, unknown>) => {
    return taxCalculatorDb.taxCalculations.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteTaxCalculation: async (id: number | string) => {
    return taxCalculatorDb.taxCalculations.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

} as const;

export type TaxCalculatorQueries = typeof taxCalculatorQueries;

// --- end auto-generated ---

