// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Receipt Scanner - offline-first query helpers.
//
// Rules:
//   * Writes go to Dexie first with syncStatus = 'pending'.
//   * Background sync worker reconciles with /api/v1/* later.
//   * Reads are user-scoped where the table has a userId/ownerId.
//   * Monetary writes that mutate balances MUST be confirmed by the
//     server-authoritative endpoint before being marked synced.

import { receiptScannerDb } from './db';

export const receiptScannerQueries = {
  /** List all local rows in `expenseBills`. */
  listExpenseBills: async () => receiptScannerDb.expenseBills.toArray(),

  /** Get a single `expenseBill` by primary key. */
  getExpenseBill: async (id: number | string) => receiptScannerDb.expenseBills.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createExpenseBill: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return receiptScannerDb.expenseBills.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateExpenseBill: async (id: number | string, patch: Record<string, unknown>) => {
    return receiptScannerDb.expenseBills.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteExpenseBill: async (id: number | string) => {
    return receiptScannerDb.expenseBills.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** List all local rows in `documents`. */
  listDocuments: async () => receiptScannerDb.documents.toArray(),

  /** Get a single `document` by primary key. */
  getDocument: async (id: number | string) => receiptScannerDb.documents.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createDocument: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return receiptScannerDb.documents.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateDocument: async (id: number | string, patch: Record<string, unknown>) => {
    return receiptScannerDb.documents.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteDocument: async (id: number | string) => {
    return receiptScannerDb.documents.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

} as const;

export type ReceiptScannerQueries = typeof receiptScannerQueries;

// --- end auto-generated ---

