# PowerShell mirror of scripts/scaffold-feature-schemas.ts.
$ErrorActionPreference = 'Stop'
$root        = Split-Path -Parent $PSScriptRoot
$schemaPath  = Join-Path $root 'prisma\schema.prisma'
$featuresDir = Join-Path $root 'src\features'
$bt          = [char]96
$mdBanner    = '<!-- AUTO-GENERATED by scripts/scaffold-feature-schemas.ts. Do not edit by hand. -->'
$tsBanner    = '// AUTO-GENERATED by scripts/scaffold-feature-schemas.ts. Safe to extend below the marker.'
$tsMarker    = '// --- end auto-generated ---'
$featureModels = [ordered]@{
  aa             = @('AaConsent','AaConsentArtifact','AaDataSession','AaFinancialData','AaTransaction')
  accounts       = @('Account')
  admin          = @('AuditLog','PlatformSettings')
  advisors       = @('AdvisorApplication','AdvisorAvailability','AdvisorSession')
  ai             = @('AiScan','ai_events','ai_insights','ai_model_runs')
  auth           = @('User','RefreshToken','profiles')
  avatars        = @()
  bills          = @('ExpenseBill')
  bookings       = @('BookingRequest')
  budgets        = @('Budget')
  categorization = @('Category')
  collaboration  = @('CollaborationParticipant','ChatMessage')
  dashboard      = @()
  devices        = @('Device')
  friends        = @('Friend')
  goals          = @('Goal','GoalContribution','GoalMember')
  gold           = @('GoldAsset')
  groups         = @('GroupExpense','GroupExpenseMember')
  import         = @('ImportLog')
  investments    = @('Investment')
  loans          = @('Loan','LoanPayment')
  notifications  = @('Notification')
  otp            = @('OtpCode','OtpRequest')
  payments       = @('Payment')
  pin            = @('UserPin')
  receipts       = @()
  recurring      = @('RecurringTransaction')
  sessions       = @()
  settings       = @('UserSettings','user_features')
  stocks         = @()
  sync           = @('SyncQueue')
  todos          = @('Todo')
  transactions   = @('Transaction')
  voice          = @()
  webhooks       = @()
}
$src = Get-Content -Raw -LiteralPath $schemaPath
$models = @{}
$regex = [regex]'(?ms)^model\s+(\w+)\s*\{.*?^\}'
foreach ($m in $regex.Matches($src)) { $models[$m.Groups[1].Value] = $m.Value }
function To-Pascal([string]$n) {
  $parts = $n -split '[-_]'; $out = ''
  foreach ($p in $parts) { if ($p) { $out += $p.Substring(0,1).ToUpper() + $p.Substring(1) } }
  return $out
}
function Should-Write([string]$path, [string]$expectedBanner) {
  if (-not (Test-Path -LiteralPath $path)) { return $true }
  $first = Get-Content -LiteralPath $path -TotalCount 1
  if ($null -eq $first) { return $true }
  return ($first -eq $expectedBanner)
}
$schemaCount = 0; $queriesCount = 0; $unknown = @()
$features = Get-ChildItem -LiteralPath $featuresDir -Directory | Sort-Object Name
foreach ($f in $features) {
  $feature = $f.Name
  if (-not $featureModels.Contains($feature)) { $unknown += $feature; continue }
  $owned = $featureModels[$feature]
  $featureDir = $f.FullName
  $files = Get-ChildItem -LiteralPath $featureDir -File | ForEach-Object { $_.Name }
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add($mdBanner); $lines.Add('')
  $lines.Add('# ' + $bt + $feature + $bt + ' - database schema slice'); $lines.Add('')
  $lines.Add('Source of truth: [' + $bt + 'backend/prisma/schema.prisma' + $bt + '](../../../prisma/schema.prisma).')
  $lines.Add('This file mirrors the Prisma models owned by this feature so the schema is')
  $lines.Add('co-located with the code that reads/writes it. Regenerate via:'); $lines.Add('')
  $lines.Add($bt + $bt + $bt + 'bash')
  $lines.Add('pwsh backend/scripts/scaffold-feature-schemas.ps1')
  $lines.Add($bt + $bt + $bt); $lines.Add('')
  $missing = @()
  if ($owned.Count -eq 0) { $lines.Add('_No Prisma models are owned directly by this feature._') }
  else {
    foreach ($name in $owned) {
      if (-not $models.ContainsKey($name)) { $missing += $name; continue }
      $lines.Add('## ' + $bt + $name + $bt); $lines.Add('')
      $lines.Add($bt + $bt + $bt + 'prisma'); $lines.Add($models[$name])
      $lines.Add($bt + $bt + $bt); $lines.Add('')
    }
  }
  if ($missing.Count -gt 0) {
    $lines.Add('')
    $bullets = ($missing | ForEach-Object { $bt + $_ + $bt }) -join ', '
    $lines.Add('> [warn] Missing in ' + $bt + 'schema.prisma' + $bt + ': ' + $bullets)
  }
  Set-Content -LiteralPath (Join-Path $featureDir 'schema.prisma.md') -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
  $schemaCount++
  $repoFile = $files | Where-Object { $_ -match '\.repository\.ts$' } | Select-Object -First 1
  $valFile  = $files | Where-Object { $_ -match '\.validation\.ts$' } | Select-Object -First 1
  $repoClass = $null
  if ($repoFile) { $base = $repoFile -replace '\.repository\.ts$',''; $repoClass = (To-Pascal $base) + 'Repository' }
  $q = New-Object System.Collections.Generic.List[string]
  $q.Add($tsBanner)
  $q.Add('// Feature: ' + $feature); $q.Add('//')
  $q.Add('// Uniform per-feature query entry-point. Import from here instead of')
  $q.Add('// reaching into the repository directly - this gives every feature the')
  $q.Add('// same surface (queries) and lets us evolve internals (Prisma -> raw')
  $q.Add('// SQL, caching, etc.) without rippling import paths.'); $q.Add('//')
  $q.Add('// Ownership + monetary-integrity rules MUST live in the service layer;')
  $q.Add('// queries is a thin, typed data-access facade.'); $q.Add('')
  if ($repoFile -and $repoClass) {
    $imp = './' + ($repoFile -replace '\.ts$','')
    $q.Add("import { $repoClass } from '$imp';")
  }
  if ($valFile) {
    $vimp = './' + ($valFile -replace '\.ts$','')
    $q.Add("export * as schemas from '$vimp';")
  }
  $q.Add('')
  if ($repoClass) {
    $q.Add("/** Singleton repository instance for the $feature feature. */")
    $q.Add("export const ${feature}Queries = new $repoClass();"); $q.Add('')
    $tname = To-Pascal $feature
    $q.Add("export type ${tname}Queries = typeof ${feature}Queries;")
  } else {
    $q.Add("// No repository found for feature '$feature' yet. Add a *.repository.ts and re-run")
    $q.Add('// pwsh backend/scripts/scaffold-feature-schemas.ps1 to wire it up.')
    $q.Add("export const ${feature}Queries = {} as const;")
  }
  $q.Add(''); $q.Add($tsMarker); $q.Add('')
  $queriesTarget = Join-Path $featureDir 'queries.ts'
  if (Should-Write $queriesTarget $tsBanner) {
    Set-Content -LiteralPath $queriesTarget -Value ($q -join [Environment]::NewLine) -Encoding UTF8
    $queriesCount++
  }
}
Write-Host ("[OK] wrote {0} schema slices, {1} queries.ts files" -f $schemaCount, $queriesCount)
if ($unknown.Count -gt 0) { Write-Warning ('Unmapped feature folders: ' + ($unknown -join ', ')) }
