/**
 * Scaffolds per-feature `schema.prisma.md` (model slice mirror) and
 * `queries.ts` (uniform typed query entry-point) for every directory under
 * `backend/src/features/`.
 *
 * - The monolithic `prisma/schema.prisma` remains the source of truth for the
 *   Prisma CLI (migrations, generate). We mirror the relevant model blocks
 *   into each feature folder so the schema is discoverable next to the code
 *   that owns it.
 * - `queries.ts` re-exports the existing `*.repository.ts` instance under a
 *   stable name and provides a typed surface other features can import.
 *
 * Re-run safely: existing files with the `AUTO-GENERATED` banner are
 * overwritten; hand-edited files (without the banner) are left untouched.
 *
 * Usage:  pnpm -F backend tsx scripts/scaffold-feature-schemas.ts
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(__dirname, '..');
const SCHEMA_PATH = path.join(ROOT, 'prisma', 'schema.prisma');
const FEATURES_DIR = path.join(ROOT, 'src', 'features');
const BANNER = '<!-- AUTO-GENERATED by scripts/scaffold-feature-schemas.ts. Do not edit by hand. -->';
const TS_BANNER = '// AUTO-GENERATED by scripts/scaffold-feature-schemas.ts. Safe to extend below the marker.';
const TS_MARKER = '// --- end auto-generated ---';

/** Maps each feature folder to the Prisma models it owns. */
const FEATURE_MODELS: Record<string, readonly string[]> = {
  aa: ['AaConsent', 'AaConsentArtifact', 'AaDataSession', 'AaFinancialData', 'AaTransaction'],
  accounts: ['Account'],
  admin: ['AuditLog', 'PlatformSettings'],
  advisors: ['AdvisorApplication', 'AdvisorAvailability', 'AdvisorSession'],
  ai: ['AiScan', 'ai_events', 'ai_insights', 'ai_model_runs'],
  auth: ['User', 'RefreshToken', 'profiles'],
  avatars: [],
  bills: ['ExpenseBill'],
  bookings: ['BookingRequest'],
  budgets: ['Budget'],
  categorization: ['Category'],
  collaboration: ['CollaborationParticipant', 'ChatMessage'],
  dashboard: [],
  devices: ['Device'],
  friends: ['Friend'],
  goals: ['Goal', 'GoalContribution', 'GoalMember'],
  gold: ['GoldAsset'],
  groups: ['GroupExpense', 'GroupExpenseMember'],
  import: ['ImportLog'],
  investments: ['Investment'],
  loans: ['Loan', 'LoanPayment'],
  notifications: ['Notification'],
  otp: ['OtpCode', 'OtpRequest'],
  payments: ['Payment'],
  pin: ['UserPin'],
  receipts: [],
  recurring: ['RecurringTransaction'],
  sessions: [],
  settings: ['UserSettings', 'user_features'],
  stocks: [],
  sync: ['SyncQueue'],
  todos: ['Todo'],
  transactions: ['Transaction'],
  voice: [],
  webhooks: [],
};

interface ParsedModel {
  name: string;
  block: string; // full `model X { ... }` text
}

async function parsePrismaModels(schemaPath: string): Promise<Map<string, ParsedModel>> {
  const src = await fs.readFile(schemaPath, 'utf8');
  const models = new Map<string, ParsedModel>();
  // Match: model <Name> { ... } (non-greedy, brace-balanced for simple Prisma blocks)
  const re = /^model\s+(\w+)\s*\{[\s\S]*?^\}/gm;
  let match: RegExpExecArray | null;
  while ((match = re.exec(src)) !== null) {
    models.set(match[1], { name: match[1], block: match[0] });
  }
  return models;
}

function findRepositoryFile(featureDir: string, files: string[]): string | null {
  const repo = files.find((f) => /\.repository\.ts$/.test(f));
  return repo ?? null;
}

function findValidationFile(files: string[]): string | null {
  return files.find((f) => /\.validation\.ts$/.test(f)) ?? null;
}

function pascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

async function writeSchemaSlice(featureDir: string, feature: string, modelNames: readonly string[], models: Map<string, ParsedModel>) {
  const target = path.join(featureDir, 'schema.prisma.md');
  const owned = modelNames.map((m) => models.get(m)).filter((x): x is ParsedModel => Boolean(x));
  const missing = modelNames.filter((m) => !models.has(m));
  const header = [
    BANNER,
    '',
    `# \`${feature}\` — database schema slice`,
    '',
    'Source of truth: [`backend/prisma/schema.prisma`](../../../prisma/schema.prisma).',
    'This file mirrors the Prisma models owned by this feature so the schema is',
    'co-located with the code that reads/writes it. Regenerate via:',
    '',
    '```bash',
    'pnpm -F backend tsx scripts/scaffold-feature-schemas.ts',
    '```',
    '',
  ].join('\n');

  const body = owned.length === 0
    ? '_No Prisma models are owned directly by this feature._\n'
    : owned
        .map((m) => `## \`${m.name}\`\n\n\`\`\`prisma\n${m.block}\n\`\`\`\n`)
        .join('\n');

  const footer = missing.length > 0
    ? `\n> ⚠️ Missing in \`schema.prisma\`: ${missing.map((m) => `\`${m}\``).join(', ')}\n`
    : '';

  await fs.writeFile(target, `${header}\n${body}${footer}`, 'utf8');
}

async function writeQueriesFile(featureDir: string, feature: string, repoFile: string | null, validationFile: string | null) {
  const target = path.join(featureDir, 'queries.ts');
  // Preserve hand-written queries.ts (no banner) as-is.
  try {
    const existing = await fs.readFile(target, 'utf8');
    if (!existing.startsWith(TS_BANNER)) return;
  } catch {
    /* file doesn't exist — create it */
  }

  const repoImport = repoFile ? `./${repoFile.replace(/\.ts$/, '')}` : null;
  const valImport = validationFile ? `./${validationFile.replace(/\.ts$/, '')}` : null;
  const repoClass = repoFile ? `${pascal(repoFile.replace(/\.repository\.ts$/, ''))}Repository` : null;

  const lines: string[] = [TS_BANNER];
  lines.push(`// Feature: ${feature}`);
  lines.push('//');
  lines.push('// Uniform per-feature query entry-point. Import from here instead of');
  lines.push('// reaching into the repository directly — this gives every feature the');
  lines.push("// same surface ('queries') and lets us evolve internals (Prisma -> raw");
  lines.push('// SQL, caching, etc.) without rippling import paths.');
  lines.push('//');
  lines.push('// Ownership + monetary-integrity rules MUST live in the service layer;');
  lines.push('// `queries` is a thin, typed data-access façade.');
  lines.push('');
  if (repoImport && repoClass) {
    lines.push(`import { ${repoClass} } from '${repoImport}';`);
  }
  if (valImport) {
    lines.push(`export * as schemas from '${valImport}';`);
  }
  lines.push('');
  if (repoClass) {
    lines.push(`/** Singleton repository instance for the ${feature} feature. */`);
    lines.push(`export const ${feature}Queries = new ${repoClass}();`);
    lines.push('');
    lines.push(`export type ${pascal(feature)}Queries = typeof ${feature}Queries;`);
  } else {
    lines.push(`// No repository found for "${feature}" yet. Add a *.repository.ts and re-run`);
    lines.push('// `pnpm -F backend tsx scripts/scaffold-feature-schemas.ts` to wire it up.');
    lines.push(`export const ${feature}Queries = {} as const;`);
  }
  lines.push('');
  lines.push(TS_MARKER);
  lines.push('');

  await fs.writeFile(target, lines.join('\n'), 'utf8');
}

async function main() {
  const models = await parsePrismaModels(SCHEMA_PATH);
  const entries = await fs.readdir(FEATURES_DIR, { withFileTypes: true });
  const features = entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();

  let schemaCount = 0;
  let queriesCount = 0;
  const unknown: string[] = [];

  for (const feature of features) {
    const featureDir = path.join(FEATURES_DIR, feature);
    const owned = FEATURE_MODELS[feature];
    if (owned === undefined) {
      unknown.push(feature);
      continue;
    }
    const files = await fs.readdir(featureDir);
    await writeSchemaSlice(featureDir, feature, owned, models);
    schemaCount++;
    await writeQueriesFile(featureDir, feature, findRepositoryFile(featureDir, files), findValidationFile(files));
    queriesCount++;
  }

  // eslint-disable-next-line no-console
  console.log(`✓ wrote ${schemaCount} schema slices, ${queriesCount} queries.ts files`);
  if (unknown.length > 0) {
    // eslint-disable-next-line no-console
    console.warn(`! unmapped feature folders (add to FEATURE_MODELS): ${unknown.join(', ')}`);
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});

