ALTER TABLE public.profiles 
  ADD COLUMN IF NOT EXISTS gender TEXT,
  ADD COLUMN IF NOT EXISTS date_of_birth TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS monthly_income DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS annual_income DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS job_type TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS avatar_id TEXT;
