// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Contact (marketing)
// Component: frontend/src/app/components/marketing/ContactPage.tsx
//
// Co-located Dexie schema slice. Re-exports the page-relevant tables from
// the shared `db` instance so feature code only sees what it owns.
// The actual schema versions / .stores() live in `src/lib/database.ts`
// to keep a single IndexedDB per app.

import { db } from '../../lib/database';

// Contact (marketing) has no local-first tables (server-only or static page).
export const contactDb = {} as const;

// --- end auto-generated ---

