/**
 * Scaffolds per-page `db.ts` (Dexie table refs) and `queries.ts` (offline-first
 * query helpers) under `frontend/src/pages/<page>/` for every known page.
 *
 * Design constraints (see .github/copilot-instructions.md):
 *  - Local-first: every write goes through Dexie with `syncStatus: 'pending'`
 *    and is later reconciled by the sync worker.
 *  - User-scoped: queries take an explicit `userId` (or `ownerId`) where the
 *    table carries one.
 *  - No `any`: tables are typed via the central `db` instance in
 *    `frontend/src/lib/database.ts`.
 *  - Non-breaking: existing page components stay where they are; the data
 *    slice is co-located by name under `pages/<page>/`.
 *
 * Re-run safely: only overwrites files that start with the AUTO-GENERATED
 * banner. Hand-edited files are preserved.
 *
 * Usage:  pnpm -F frontend tsx scripts/scaffold-page-db.ts
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(__dirname, '..');
const PAGES_DIR = path.join(ROOT, 'src', 'pages');
const BANNER = '// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.';
const MARKER = '// --- end auto-generated ---';

interface PageSpec {
  /** kebab-case folder name under src/pages */
  slug: string;
  /** Human-friendly title used in JSDoc */
  title: string;
  /** Dexie table property names on the shared `db` instance */
  tables: readonly string[];
  /** Where the page component lives (for the JSDoc back-reference) */
  componentPath: string;
}

const PAGES: readonly PageSpec[] = [
  { slug: 'auth', title: 'Auth', tables: [], componentPath: 'app/components/auth/AuthPage.tsx' },
  { slug: 'ai-insights', title: 'AI Insights', tables: ['transactions', 'categories'], componentPath: 'app/components/features/AIInsightsPage.tsx' },
  { slug: 'budget-alerts', title: 'Budget Alerts', tables: ['budgets', 'budgetAlerts'], componentPath: 'app/components/features/BudgetAlertsPage.tsx' },
  { slug: 'client-management', title: 'Client Management', tables: ['friends', 'advisorAssignments'], componentPath: 'app/components/features/ClientManagementPage.tsx' },
  { slug: 'receipt-scanner', title: 'Receipt Scanner', tables: ['expenseBills', 'documents'], componentPath: 'app/components/features/ReceiptScannerPage.tsx' },
  { slug: 'tax-calculator', title: 'Tax Calculator', tables: ['taxCalculations'], componentPath: 'app/components/features/TaxCalculatorPage.tsx' },
  { slug: 'voice-assistant', title: 'Voice Assistant', tables: [], componentPath: 'pages/VoiceAssistantPage.tsx' },
  { slug: 'about', title: 'About (marketing)', tables: [], componentPath: 'app/components/marketing/AboutPage.tsx' },
  { slug: 'contact', title: 'Contact (marketing)', tables: [], componentPath: 'app/components/marketing/ContactPage.tsx' },
  { slug: 'landing', title: 'Landing (marketing)', tables: [], componentPath: 'app/components/marketing/LandingPage.tsx' },
  { slug: 'pricing', title: 'Pricing (marketing)', tables: [], componentPath: 'app/components/marketing/PricingPage.tsx' },
];

function camel(slug: string): string {
  return slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function pascal(slug: string): string {
  const c = camel(slug);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true });
}

async function shouldWrite(target: string): Promise<boolean> {
  try {
    const existing = await fs.readFile(target, 'utf8');
    return existing.startsWith(BANNER);
  } catch {
    return true;
  }
}

function dbFile(page: PageSpec): string {
  const lines: string[] = [BANNER];
  lines.push(`// Page: ${page.title}`);
  lines.push(`// Component: frontend/src/${page.componentPath}`);
  lines.push('//');
  lines.push('// Co-located Dexie schema slice. Re-exports the page-relevant tables from');
  lines.push('// the shared `db` instance so feature code only sees what it owns.');
  lines.push('// The actual schema versions / .stores() live in `src/lib/database.ts`');
  lines.push('// to keep a single IndexedDB per app.');
  lines.push('');
  lines.push("import { db } from '../../lib/database';");
  lines.push('');
  if (page.tables.length === 0) {
    lines.push(`// ${page.title} has no local-first tables (server-only or static page).`);
    lines.push(`export const ${camel(page.slug)}Db = {} as const;`);
  } else {
    lines.push(`export const ${camel(page.slug)}Db = {`);
    for (const t of page.tables) {
      lines.push(`  ${t}: db.${t},`);
    }
    lines.push('} as const;');
    lines.push('');
    lines.push(`export type ${pascal(page.slug)}Db = typeof ${camel(page.slug)}Db;`);
  }
  lines.push('');
  lines.push(MARKER);
  lines.push('');
  return lines.join('\n');
}

function queriesFile(page: PageSpec): string {
  const lines: string[] = [BANNER];
  lines.push(`// Page: ${page.title} — offline-first query helpers.`);
  lines.push('//');
  lines.push('// Rules:');
  lines.push("//   * Writes go to Dexie first with syncStatus = 'pending'.");
  lines.push('//   * Background sync worker reconciles with /api/v1/* later.');
  lines.push('//   * Reads are user-scoped where the table has a userId/ownerId.');
  lines.push('//   * Monetary writes that mutate balances MUST be confirmed by the');
  lines.push('//     server-authoritative endpoint before being marked synced.');
  lines.push('');
  lines.push(`import { ${camel(page.slug)}Db } from './db';`);
  lines.push('');
  if (page.tables.length === 0) {
    lines.push(`export const ${camel(page.slug)}Queries = {} as const;`);
  } else {
    lines.push(`export const ${camel(page.slug)}Queries = {`);
    for (const t of page.tables) {
      const single = t.endsWith('s') ? t.slice(0, -1) : t;
      lines.push(`  /** List all local rows in \`${t}\` (most-recent first when an updatedAt index exists). */`);
      lines.push(`  list${pascal(t)}: async () => ${camel(page.slug)}Db.${t}.toArray(),`);
      lines.push('');
      lines.push(`  /** Get a single \`${single}\` by primary key. */`);
      lines.push(`  get${pascal(single)}: async (id: number | string) => ${camel(page.slug)}Db.${t}.get(id as never),`);
      lines.push('');
      lines.push(`  /** Local-first create: stores with syncStatus = 'pending'. */`);
      lines.push(`  create${pascal(single)}: async <T extends Record<string, unknown>>(input: T) => {`);
      lines.push(`    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };`);
      lines.push(`    return ${camel(page.slug)}Db.${t}.add(row as never);`);
      lines.push('  },');
      lines.push('');
      lines.push(`  /** Local-first update: re-marks the row as pending for the sync worker. */`);
      lines.push(`  update${pascal(single)}: async (id: number | string, patch: Record<string, unknown>) => {`);
      lines.push(`    return ${camel(page.slug)}Db.${t}.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);`);
      lines.push('  },');
      lines.push('');
      lines.push(`  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */`);
      lines.push(`  delete${pascal(single)}: async (id: number | string) => {`);
      lines.push(`    return ${camel(page.slug)}Db.${t}.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);`);
      lines.push('  },');
      lines.push('');
    }
    lines.push('} as const;');
    lines.push('');
    lines.push(`export type ${pascal(page.slug)}Queries = typeof ${camel(page.slug)}Queries;`);
  }
  lines.push('');
  lines.push(MARKER);
  lines.push('');
  return lines.join('\n');
}

function readmeFile(page: PageSpec): string {
  return [
    `# \`${page.slug}\` page data slice`,
    '',
    `Component: \`frontend/src/${page.componentPath}\``,
    '',
    '## Files',
    '',
    '- `db.ts` — Dexie table refs scoped to this page (auto-generated).',
    '- `queries.ts` — offline-first read/write helpers (auto-generated, safe to extend below the marker).',
    '',
    page.tables.length === 0
      ? '_No local-first tables; this page is server-only or static._'
      : `## Tables\n\n${page.tables.map((t) => `- \`db.${t}\``).join('\n')}`,
    '',
    'Regenerate with:',
    '',
    '```bash',
    'pnpm -F frontend tsx scripts/scaffold-page-db.ts',
    '```',
    '',
  ].join('\n');
}

async function main() {
  await ensureDir(PAGES_DIR);
  let written = 0;
  for (const page of PAGES) {
    const dir = path.join(PAGES_DIR, page.slug);
    await ensureDir(dir);
    const dbPath = path.join(dir, 'db.ts');
    const queriesPath = path.join(dir, 'queries.ts');
    const readmePath = path.join(dir, 'README.md');
    if (await shouldWrite(dbPath)) {
      await fs.writeFile(dbPath, dbFile(page), 'utf8');
      written++;
    }
    if (await shouldWrite(queriesPath)) {
      await fs.writeFile(queriesPath, queriesFile(page), 'utf8');
      written++;
    }
    try {
      await fs.access(readmePath);
    } catch {
      await fs.writeFile(readmePath, readmeFile(page), 'utf8');
      written++;
    }
  }
  // eslint-disable-next-line no-console
  console.log(`✓ scaffolded ${written} page data-slice files across ${PAGES.length} pages`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});

