# PowerShell mirror of scripts/scaffold-page-db.ts.
$ErrorActionPreference = 'Stop'
$root     = Split-Path -Parent $PSScriptRoot
$pagesDir = Join-Path $root 'src\pages'
$banner   = '// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.'
$marker   = '// --- end auto-generated ---'
$pages = @(
  @{ slug='auth';              title='Auth';                tables=@();                                  component='app/components/auth/AuthPage.tsx' }
  @{ slug='ai-insights';       title='AI Insights';         tables=@('transactions','categories');       component='app/components/features/AIInsightsPage.tsx' }
  @{ slug='budget-alerts';     title='Budget Alerts';       tables=@('budgets','budgetAlerts');          component='app/components/features/BudgetAlertsPage.tsx' }
  @{ slug='client-management'; title='Client Management';   tables=@('friends','advisorAssignments');    component='app/components/features/ClientManagementPage.tsx' }
  @{ slug='receipt-scanner';   title='Receipt Scanner';     tables=@('expenseBills','documents');        component='app/components/features/ReceiptScannerPage.tsx' }
  @{ slug='voice-assistant';   title='Voice Assistant';     tables=@();                                  component='pages/VoiceAssistantPage.tsx' }
  @{ slug='about';             title='About (marketing)';   tables=@();                                  component='app/components/marketing/AboutPage.tsx' }
  @{ slug='contact';           title='Contact (marketing)'; tables=@();                                  component='app/components/marketing/ContactPage.tsx' }
  @{ slug='landing';           title='Landing (marketing)'; tables=@();                                  component='app/components/marketing/LandingPage.tsx' }
  @{ slug='pricing';           title='Pricing (marketing)'; tables=@();                                  component='app/components/marketing/PricingPage.tsx' }
)
function To-Camel([string]$s) { return [regex]::Replace($s, '-([a-z])', [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $m.Groups[1].Value.ToUpper() }) }
function To-Pascal([string]$s) { $c = To-Camel $s; return $c.Substring(0,1).ToUpper() + $c.Substring(1) }
function Should-Write([string]$path) {
  if (-not (Test-Path -LiteralPath $path)) { return $true }
  $first = Get-Content -LiteralPath $path -TotalCount 1
  if ($null -eq $first) { return $true }
  return ($first -eq $banner)
}
if (-not (Test-Path -LiteralPath $pagesDir)) { New-Item -ItemType Directory -Force -Path $pagesDir | Out-Null }
$written = 0
foreach ($p in $pages) {
  $slug = $p.slug; $title = $p.title; $tables = $p.tables; $component = $p.component
  $dir = Join-Path $pagesDir $slug
  if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $cam = To-Camel $slug; $pas = To-Pascal $slug
  # db.ts
  $L = New-Object System.Collections.Generic.List[string]
  $L.Add($banner)
  $L.Add('// Page: ' + $title)
  $L.Add('// Component: frontend/src/' + $component)
  $L.Add('//')
  $L.Add('// Co-located Dexie schema slice. Re-exports the page-relevant tables from')
  $L.Add('// the shared `db` instance so feature code only sees what it owns.')
  $L.Add('// The actual schema versions / .stores() live in `src/lib/database.ts`')
  $L.Add('// to keep a single IndexedDB per app.')
  $L.Add('')
  $L.Add("import { db } from '../../lib/database';")
  $L.Add('')
  if ($tables.Count -eq 0) {
    $L.Add('// ' + $title + ' has no local-first tables (server-only or static page).')
    $L.Add('export const ' + $cam + 'Db = {} as const;')
  } else {
    $L.Add('export const ' + $cam + 'Db = {')
    foreach ($t in $tables) { $L.Add('  ' + $t + ': db.' + $t + ',') }
    $L.Add('} as const;')
    $L.Add('')
    $L.Add('export type ' + $pas + 'Db = typeof ' + $cam + 'Db;')
  }
  $L.Add(''); $L.Add($marker); $L.Add('')
  $dbPath = Join-Path $dir 'db.ts'
  if (Should-Write $dbPath) { Set-Content -LiteralPath $dbPath -Value ($L -join [Environment]::NewLine) -Encoding UTF8; $written++ }
  # queries.ts
  $Q = New-Object System.Collections.Generic.List[string]
  $Q.Add($banner)
  $Q.Add('// Page: ' + $title + ' - offline-first query helpers.')
  $Q.Add('//')
  $Q.Add('// Rules:')
  $Q.Add("//   * Writes go to Dexie first with syncStatus = 'pending'.")
  $Q.Add('//   * Background sync worker reconciles with /api/v1/* later.')
  $Q.Add('//   * Reads are user-scoped where the table has a userId/ownerId.')
  $Q.Add('//   * Monetary writes that mutate balances MUST be confirmed by the')
  $Q.Add('//     server-authoritative endpoint before being marked synced.')
  $Q.Add('')
  $Q.Add("import { ${cam}Db } from './db';")
  $Q.Add('')
  if ($tables.Count -eq 0) {
    $Q.Add('export const ' + $cam + 'Queries = {} as const;')
  } else {
    $Q.Add('export const ' + $cam + 'Queries = {')
    foreach ($t in $tables) {
      $single = if ($t.EndsWith('s')) { $t.Substring(0, $t.Length - 1) } else { $t }
      $Tpas = (To-Pascal $t); $Spas = (To-Pascal $single)
      $Q.Add('  /** List all local rows in `' + $t + '`. */')
      $Q.Add('  list' + $Tpas + ': async () => ' + $cam + 'Db.' + $t + '.toArray(),')
      $Q.Add('')
      $Q.Add('  /** Get a single `' + $single + '` by primary key. */')
      $Q.Add('  get' + $Spas + ': async (id: number | string) => ' + $cam + 'Db.' + $t + '.get(id as never),')
      $Q.Add('')
      $Q.Add("  /** Local-first create: stores with syncStatus = 'pending'. */")
      $Q.Add('  create' + $Spas + ': async <T extends Record<string, unknown>>(input: T) => {')
      $Q.Add("    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };")
      $Q.Add('    return ' + $cam + 'Db.' + $t + '.add(row as never);')
      $Q.Add('  },')
      $Q.Add('')
      $Q.Add('  /** Local-first update: re-marks the row as pending for the sync worker. */')
      $Q.Add('  update' + $Spas + ': async (id: number | string, patch: Record<string, unknown>) => {')
      $Q.Add('    return ' + $cam + 'Db.' + $t + ".update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);")
      $Q.Add('  },')
      $Q.Add('')
      $Q.Add('  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */')
      $Q.Add('  delete' + $Spas + ': async (id: number | string) => {')
      $Q.Add('    return ' + $cam + 'Db.' + $t + ".update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);")
      $Q.Add('  },')
      $Q.Add('')
    }
    $Q.Add('} as const;')
    $Q.Add('')
    $Q.Add('export type ' + $pas + 'Queries = typeof ' + $cam + 'Queries;')
  }
  $Q.Add(''); $Q.Add($marker); $Q.Add('')
  $qPath = Join-Path $dir 'queries.ts'
  if (Should-Write $qPath) { Set-Content -LiteralPath $qPath -Value ($Q -join [Environment]::NewLine) -Encoding UTF8; $written++ }
  # README.md (only created if missing; user-editable)
  $rPath = Join-Path $dir 'README.md'
  if (-not (Test-Path -LiteralPath $rPath)) {
    $R = New-Object System.Collections.Generic.List[string]
    $R.Add('# `' + $slug + '` page data slice')
    $R.Add('')
    $R.Add('Component: `frontend/src/' + $component + '`')
    $R.Add('')
    $R.Add('## Files')
    $R.Add('')
    $R.Add('- `db.ts` - Dexie table refs scoped to this page (auto-generated).')
    $R.Add('- `queries.ts` - offline-first read/write helpers (auto-generated).')
    $R.Add('')
    if ($tables.Count -eq 0) {
      $R.Add('_No local-first tables; this page is server-only or static._')
    } else {
      $R.Add('## Tables')
      $R.Add('')
      foreach ($t in $tables) { $R.Add('- `db.' + $t + '`') }
    }
    $R.Add('')
    $R.Add('Regenerate with:')
    $R.Add('')
    $R.Add('```bash')
    $R.Add('pwsh frontend/scripts/scaffold-page-db.ps1')
    $R.Add('```')
    Set-Content -LiteralPath $rPath -Value ($R -join [Environment]::NewLine) -Encoding UTF8
    $written++
  }
}
Write-Host ('[OK] scaffolded {0} page data-slice files across {1} pages' -f $written, $pages.Count)

