// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Client Management - offline-first query helpers.
//
// Rules:
//   * Writes go to Dexie first with syncStatus = 'pending'.
//   * Background sync worker reconciles with /api/v1/* later.
//   * Reads are user-scoped where the table has a userId/ownerId.
//   * Monetary writes that mutate balances MUST be confirmed by the
//     server-authoritative endpoint before being marked synced.

import { clientManagementDb } from './db';

export const clientManagementQueries = {
  /** List all local rows in `friends`. */
  listFriends: async () => clientManagementDb.friends.toArray(),

  /** Get a single `friend` by primary key. */
  getFriend: async (id: number | string) => clientManagementDb.friends.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createFriend: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return clientManagementDb.friends.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateFriend: async (id: number | string, patch: Record<string, unknown>) => {
    return clientManagementDb.friends.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteFriend: async (id: number | string) => {
    return clientManagementDb.friends.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** List all local rows in `advisorAssignments`. */
  listAdvisorAssignments: async () => clientManagementDb.advisorAssignments.toArray(),

  /** Get a single `advisorAssignment` by primary key. */
  getAdvisorAssignment: async (id: number | string) => clientManagementDb.advisorAssignments.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createAdvisorAssignment: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return clientManagementDb.advisorAssignments.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateAdvisorAssignment: async (id: number | string, patch: Record<string, unknown>) => {
    return clientManagementDb.advisorAssignments.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteAdvisorAssignment: async (id: number | string) => {
    return clientManagementDb.advisorAssignments.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

} as const;

export type ClientManagementQueries = typeof clientManagementQueries;

// --- end auto-generated ---

