// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Budget Alerts
// Component: frontend/src/app/components/features/BudgetAlertsPage.tsx
//
// Co-located Dexie schema slice. Re-exports the page-relevant tables from
// the shared `db` instance so feature code only sees what it owns.
// The actual schema versions / .stores() live in `src/lib/database.ts`
// to keep a single IndexedDB per app.

import { db } from '../../lib/database';

export const budgetAlertsDb = {
  budgets: db.budgets,
  budgetAlerts: db.budgetAlerts,
} as const;

export type BudgetAlertsDb = typeof budgetAlertsDb;

// --- end auto-generated ---

