// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Budget Alerts - offline-first query helpers.
//
// Rules:
//   * Writes go to Dexie first with syncStatus = 'pending'.
//   * Background sync worker reconciles with /api/v1/* later.
//   * Reads are user-scoped where the table has a userId/ownerId.
//   * Monetary writes that mutate balances MUST be confirmed by the
//     server-authoritative endpoint before being marked synced.

import { budgetAlertsDb } from './db';

export const budgetAlertsQueries = {
  /** List all local rows in `budgets`. */
  listBudgets: async () => budgetAlertsDb.budgets.toArray(),

  /** Get a single `budget` by primary key. */
  getBudget: async (id: number | string) => budgetAlertsDb.budgets.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createBudget: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return budgetAlertsDb.budgets.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateBudget: async (id: number | string, patch: Record<string, unknown>) => {
    return budgetAlertsDb.budgets.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteBudget: async (id: number | string) => {
    return budgetAlertsDb.budgets.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** List all local rows in `budgetAlerts`. */
  listBudgetAlerts: async () => budgetAlertsDb.budgetAlerts.toArray(),

  /** Get a single `budgetAlert` by primary key. */
  getBudgetAlert: async (id: number | string) => budgetAlertsDb.budgetAlerts.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createBudgetAlert: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return budgetAlertsDb.budgetAlerts.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateBudgetAlert: async (id: number | string, patch: Record<string, unknown>) => {
    return budgetAlertsDb.budgetAlerts.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteBudgetAlert: async (id: number | string) => {
    return budgetAlertsDb.budgetAlerts.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

} as const;

export type BudgetAlertsQueries = typeof budgetAlertsQueries;

// --- end auto-generated ---

