// AUTO-GENERATED by scripts/scaffold-feature-schemas.ts. Safe to extend below the marker.
// Feature: bills
//
// Uniform per-feature query entry-point. Import from here instead of
// reaching into the repository directly - this gives every feature the
// same surface (queries) and lets us evolve internals (Prisma -> raw
// SQL, caching, etc.) without rippling import paths.
//
// Ownership + monetary-integrity rules MUST live in the service layer;
// queries is a thin, typed data-access facade.

export * as schemas from './bills.validation';

// No repository found for feature 'bills' yet. Add a *.repository.ts and re-run
// pwsh backend/scripts/scaffold-feature-schemas.ps1 to wire it up.
export const billsQueries = {} as const;

// --- end auto-generated ---

