// AUTO-GENERATED by scripts/scaffold-feature-schemas.ts. Safe to extend below the marker.
// Feature: accounts
//
// Uniform per-feature query entry-point. Import from here instead of
// reaching into the repository directly - this gives every feature the
// same surface (queries) and lets us evolve internals (Prisma -> raw
// SQL, caching, etc.) without rippling import paths.
//
// Ownership + monetary-integrity rules MUST live in the service layer;
// queries is a thin, typed data-access facade.

import { AccountRepository } from './account.repository';
export * as schemas from './account.validation';

/** Singleton repository instance for the accounts feature. */
export const accountsQueries = new AccountRepository();

export type AccountsQueries = typeof accountsQueries;

// --- end auto-generated ---

