// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: AI Insights
// Component: frontend/src/app/components/features/AIInsightsPage.tsx
//
// Co-located Dexie schema slice. Re-exports the page-relevant tables from
// the shared `db` instance so feature code only sees what it owns.
// The actual schema versions / .stores() live in `src/lib/database.ts`
// to keep a single IndexedDB per app.

import { db } from '../../lib/database';

export const aiInsightsDb = {
  transactions: db.transactions,
  categories: db.categories,
} as const;

export type AiInsightsDb = typeof aiInsightsDb;

// --- end auto-generated ---

