// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: AI Insights - offline-first query helpers.
//
// Rules:
//   * Writes go to Dexie first with syncStatus = 'pending'.
//   * Background sync worker reconciles with /api/v1/* later.
//   * Reads are user-scoped where the table has a userId/ownerId.
//   * Monetary writes that mutate balances MUST be confirmed by the
//     server-authoritative endpoint before being marked synced.

import { aiInsightsDb } from './db';

export const aiInsightsQueries = {
  /** List all local rows in `transactions`. */
  listTransactions: async () => aiInsightsDb.transactions.toArray(),

  /** Get a single `transaction` by primary key. */
  getTransaction: async (id: number | string) => aiInsightsDb.transactions.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createTransaction: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return aiInsightsDb.transactions.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateTransaction: async (id: number | string, patch: Record<string, unknown>) => {
    return aiInsightsDb.transactions.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteTransaction: async (id: number | string) => {
    return aiInsightsDb.transactions.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** List all local rows in `categories`. */
  listCategories: async () => aiInsightsDb.categories.toArray(),

  /** Get a single `categorie` by primary key. */
  getCategorie: async (id: number | string) => aiInsightsDb.categories.get(id as never),

  /** Local-first create: stores with syncStatus = 'pending'. */
  createCategorie: async <T extends Record<string, unknown>>(input: T) => {
    const row = { ...input, syncStatus: 'pending', createdAt: new Date(), updatedAt: new Date() } as T & { syncStatus: 'pending' };
    return aiInsightsDb.categories.add(row as never);
  },

  /** Local-first update: re-marks the row as pending for the sync worker. */
  updateCategorie: async (id: number | string, patch: Record<string, unknown>) => {
    return aiInsightsDb.categories.update(id as never, { ...patch, syncStatus: 'pending', updatedAt: new Date() } as never);
  },

  /** Soft-delete: marks deletedAt + pending so the sync worker can propagate. */
  deleteCategorie: async (id: number | string) => {
    return aiInsightsDb.categories.update(id as never, { deletedAt: new Date(), syncStatus: 'pending', updatedAt: new Date() } as never);
  },

} as const;

export type AiInsightsQueries = typeof aiInsightsQueries;

// --- end auto-generated ---

