// AUTO-GENERATED by scripts/scaffold-page-db.ts. Safe to extend below the marker.
// Page: Voice Assistant - offline-first query helpers.
//
// Rules:
//   * Writes go to Dexie first with syncStatus = 'pending'.
//   * Background sync worker reconciles with /api/v1/* later.
//   * Reads are user-scoped where the table has a userId/ownerId.
//   * Monetary writes that mutate balances MUST be confirmed by the
//     server-authoritative endpoint before being marked synced.

import { voiceAssistantDb } from './db';

export const voiceAssistantQueries = {} as const;

// --- end auto-generated ---

